socketServer::Player
Game socketServer.Player.game
Referenced by socketServer.Player.run, socketServer.Player.setGame.
Socket socketServer.Player.socket
Referenced by socketServer.Player.Player, socketServer.Player.setup.
Scanner socketServer.Player.input
Referenced by socketServer.Player.run, socketServer.Player.setup.
DataOutputStream socketServer.Player.outputStream
Referenced by socketServer.Player.setup.
int socketServer.Player.playerId
Referenced by socketServer.Player.getPlayerId, socketServer.Player.Player, socketServer.Player.run.
int socketServer.Player.startMoveField
Referenced by socketServer.Player.run.
int socketServer.Player.endMoveField
Referenced by socketServer.Player.run.
PrintWriter socketServer.Player.output
Referenced by socketServer.Player.sendMessage, socketServer.Player.setup.
socketServer.Player.Player(Socket socket, int playerId)
Basic constructor socket server socket playerId this player id
References socketServer.Player.playerId, socketServer.Player.setup, socketServer.Player.socket.
void socketServer.Player.run()
Takes suitable actions according to data received from the client
References socketServer.Player.endMoveField, socketServer.Player.game, socketServer.Player.input, Game.Game.move, socketServer.Player.playerId, Game.Game.showPossibilities, socketServer.Player.startMoveField.
void socketServer.Player.setGame(Game game)
Assigns game to the player. game the game assigned to this player
References socketServer.Player.game.
int socketServer.Player.getPlayerId()
returns this player ID
References socketServer.Player.playerId.
Referenced by Games.Trylma.ServerTest.ifPlayerCouldMove, Games.Trylma.ServerTest.setAvailableFields, Games.Trylma.ServerTest.whoWinTheGame.
void socketServer.Player.sendMessage(String message)
Sends given message to the player message given message
References socketServer.Player.output.
void socketServer.Player.setup()
Sets up all necessary tools IOException exception
References socketServer.Player.input, socketServer.Player.output, socketServer.Player.outputStream, socketServer.Player.socket.
Referenced by socketServer.Player.Player.