Board::BoardField
PlayerColor Board.BoardField.playerColor
Referenced by Board.BoardField.getPlayerColor, Board.BoardField.setPlayerColor.
StatusColor Board.BoardField.statusColor
Referenced by Board.BoardField.getStatusColor, Board.BoardField.setStatusColor.
double Board.BoardField.xPosition
Referenced by Board.BoardField.getXPosition, Board.BoardField.setXPosition.
double Board.BoardField.yPosition
Referenced by Board.BoardField.getYPosition, Board.BoardField.setYPosition.
int Board.BoardField.row
Referenced by Board.BoardField.getRow, Board.BoardField.setRow.
int Board.BoardField.column
Referenced by Board.BoardField.getColumn, Board.BoardField.setColumn.
Board.BoardField.BoardField(int row, int column, double xPosition, double yPosition, int playerColorID, int statusColorID)
BoardField constructor, the board is made based on an int[][] array the field can be identified based on its position in that array row - the row of an array associated to this field column - the column of an array associated to this field xPosition - X axis position on the screen yPosition - Y axis position on the screen playerColorID - field current color statusColorID - field current status
References Board.PlayerColor.fromInteger, Board.StatusColor.fromInteger, Board.BoardField.setColumn, Board.BoardField.setPlayerColor, Board.BoardField.setRow, Board.BoardField.setStatusColor, Board.BoardField.setXPosition, Board.BoardField.setYPosition.
int Board.BoardField.getRow()
returns field row
References Board.BoardField.row.
Referenced by Board.JSONBoardConverter.buildJSONBoard, Game.TrylmaRules.findNeighbors, Game.TrylmaRules.isStartingFieldInTargetTriangle, Game.TrylmaRules.tryToJump.
void Board.BoardField.setRow(int row)
Sets field row row row the field is in
References Board.BoardField.row.
Referenced by Board.BoardField.BoardField.
int Board.BoardField.getColumn()
returns field column
References Board.BoardField.column.
Referenced by Board.JSONBoardConverter.buildJSONBoard, Game.TrylmaRules.findNeighbors, Game.TrylmaRules.isStartingFieldInTargetTriangle, Game.TrylmaRules.tryToJump.
void Board.BoardField.setColumn(int column)
Sets field column column column that the field is in
References Board.BoardField.column.
Referenced by Board.BoardField.BoardField.
PlayerColor Board.BoardField.getPlayerColor()
returns fields current color
References Board.BoardField.playerColor.
Referenced by Board.JSONBoardConverter.buildJSONBoard.
void Board.BoardField.setPlayerColor(PlayerColor playerColor)
Sets the field color playerColor a new player color
References Board.BoardField.playerColor.
Referenced by Board.BoardField.BoardField.
StatusColor Board.BoardField.getStatusColor()
returns what is current field status
References Board.BoardField.statusColor.
Referenced by Board.JSONBoardConverter.buildJSONBoard.
void Board.BoardField.setStatusColor(StatusColor statusColor)
Sets the field status statusColor a new field status
References Board.BoardField.statusColor.
Referenced by Board.BoardField.BoardField, Game.Game.showPossibilities.
double Board.BoardField.getXPosition()
returns field X axis position
References Board.BoardField.xPosition.
Referenced by Board.JSONBoardConverter.buildJSONBoard.
void Board.BoardField.setXPosition(double xPosition)
Sets field X axis position xPosition field X axis position
References Board.BoardField.xPosition.
Referenced by Board.BoardField.BoardField.
double Board.BoardField.getYPosition()
returns field Y axis position
References Board.BoardField.yPosition.
Referenced by Board.JSONBoardConverter.buildJSONBoard.
void Board.BoardField.setYPosition(double yPosition)
Sets field Y axis position yPosition field Y axis position
References Board.BoardField.yPosition.
Referenced by Board.BoardField.BoardField.