Games::Trylma::ServerTest
void Games.Trylma.ServerTest.calculatingMove()
References Board.JSONBoardConverter.buildJSONBoard, Games.Trylma.ServerTest.createMockedPlayer, Game.Game.getBoard, Game.Game.getInitializationData, Game.Game.move.
void Games.Trylma.ServerTest.whoWinTheGame()
References Games.Trylma.ServerTest.createMockedPlayer, Board.PlayerColor.fromInteger, Game.Game.getBoard, socketServer.Player.getPlayerId, Game.Game.getRules, Game.TrylmaRules.isWinner.
void Games.Trylma.ServerTest.ifPlayerCouldMove()
References Games.Trylma.ServerTest.createMockedPlayer, socketServer.Player.getPlayerId, Game.Game.move, Game.Game.setCurrentPlayer.
void Games.Trylma.ServerTest.setAvailableFields()
References Games.Trylma.ServerTest.createMockedPlayer, Game.TrylmaRules.getAvailableFields, socketServer.Player.getPlayerId, Game.Game.getRules, Game.Game.setCurrentPlayer, Game.Game.showPossibilities.
Player Games.Trylma.ServerTest.createMockedPlayer()
Referenced by Games.Trylma.ServerTest.calculatingMove, Games.Trylma.ServerTest.ifPlayerCouldMove, Games.Trylma.ServerTest.setAvailableFields, Games.Trylma.ServerTest.whoWinTheGame.