frontend::ApplicationWindow
DefaultBoardBuilder frontend.ApplicationWindow.builder
Referenced by frontend.ApplicationWindow.setBoard.
PlayerInfoPanel frontend.ApplicationWindow.infoPanel
Referenced by frontend.ApplicationWindow.ApplicationWindow.
PlayerColor frontend.ApplicationWindow.playerColor
Referenced by frontend.ApplicationWindow.ApplicationWindow.
DefaultBoard frontend.ApplicationWindow.board
Referenced by frontend.ApplicationWindow.getBoard.
frontend.ApplicationWindow.ApplicationWindow(PlayerColor playerColor, int currentPlayerID, String JSONBoard)
Basic Constructor playerColor the color of our fields currentPlayerID id of a current player JSONBoard json board received from server
References frontend.ApplicationWindow.infoPanel, frontend.ApplicationWindow.playerColor, frontend.ApplicationWindow.setBoard, frontend.ApplicationWindow.setCurrPlayer.
void frontend.ApplicationWindow.setCurrPlayer(int currPlayerID)
Changes data and displayed info about current player currPlayerID id of a current player
References board.PlayerColor.fromInteger, frontend.ApplicationWindow.ifYouCurrentPlayer, frontend.PlayerInfoPanel.setCurrentPlayerInfo.
Referenced by frontend.ApplicationWindow.ApplicationWindow, socketClient.SocketClient.play.
void frontend.ApplicationWindow.ifYouCurrentPlayer(int currPlayer)
Gives us ability to make a move if we are the current player currPlayer id of a current player
References board.PlayerColor.fromInteger, board.DefaultBoard.setActive.
Referenced by frontend.ApplicationWindow.setCurrPlayer.
Board frontend.ApplicationWindow.getBoard()
returns app board
References frontend.ApplicationWindow.board.
Referenced by socketClient.SocketClient.listenSocket, socketClient.SocketClient.play.
void frontend.ApplicationWindow.setBoard(String jsonBoard)
Sets and refreshes player board based on information from the server jsonBoard json string with board from server
References frontend.ApplicationWindow.builder, board.DefaultBoardBuilder.getDefaultBoard, board.DefaultBoardBuilder.setBoardFields.
Referenced by frontend.ApplicationWindow.ApplicationWindow, socketClient.SocketClient.play.