Board::DefaultBoardBuilder
DefaultBoard Board.DefaultBoardBuilder.board
Referenced by Board.DefaultBoardBuilder.getDefaultBoard.
void Board.DefaultBoardBuilder.initializeBoardFields(int[][] boardShape)
Initializes game board (its fields) based on given int[][] array boardShape an array describing fields positions
References Board.DefaultStartFields.addField, Board.StatusColor.INACTIVE, Board.PlayerColor.NO_PLAYER, Board.DefaultBoard.setFields, Board.DefaultBoard.setStartFields.
Referenced by Game.Game.Game.
void Board.DefaultBoardBuilder.setBoardFields(String JSONBoard)
builds a board based on String json JSONBoard json that contains data about the board JSONException exception when parsing json
References Board.DefaultBoard.setFields.
void Board.DefaultBoardBuilder.assignFields(int numberOfPlayers)
Assigns board fields to players according to they number numberOfPlayers number of players in the game
References Board.DefaultStartFields.setPlayerColors, Board.Board.startFields.
Referenced by Game.Game.Game.
DefaultBoard Board.DefaultBoardBuilder.getDefaultBoard()
returns a board created by the builder
References Board.DefaultBoardBuilder.board.
Referenced by Game.Game.Game.