Game::Game
int Game.Game.playersCount
int Game.Game.currentPlayer
TrylmaRules Game.Game.rules
Board Game.Game.board
JSONBoardConverter Game.Game.converter
List<Integer> Game.Game.winners
List<Player> Game.Game.players
Game.Game.Game(List< Player > players, int boardSize)
Constructor Sets all necessary variables, sends board and other info to players at the start of the game players list of players who play this game boardSize selected size of a game board
References Board.DefaultBoardBuilder.assignFields, Board.PlayerColor.BLUE, Board.DefaultBoardBuilder.getDefaultBoard, Board.BoardShapes.getSelectedBoard, Board.DefaultBoardBuilder.initializeBoardFields.
String Game.Game.getInitializationData(int playerID)
Creates all necessary data that needs to be delivered to player when starting the game playerID id of player we are sending the data all the data in form of a String
References Board.JSONBoardConverter.buildJSONBoard.
Referenced by Games.Trylma.ServerTest.calculatingMove.
synchronized void Game.Game.showPossibilities(int startMoveField, int playerId)
Method being used after player first click, based on the field he/she selected it maps available fields in game rules and sends them to player. startMoveField the field selected on first click playerId id of a player who is trying to move
References Board.StatusColor.ACTIVE, Board.JSONBoardConverter.buildJSONBoard, Board.StatusColor.POSSIBLE_MOVE, Board.BoardField.setStatusColor.
Referenced by socketServer.Player.run, Games.Trylma.ServerTest.setAvailableFields.
synchronized void Game.Game.move(int startMoveField, int endMoveField, int playerId)
Method being used after player second click, based on the field he/she selected, it checks if the move is legal and if someone won. After move sends updated board to all players startMoveField the field selected on first click endMoveField the field selected on second click playerId id of a player who is trying to move
References Board.JSONBoardConverter.buildJSONBoard, Board.PlayerColor.fromInteger, Game.TrylmaRules.moveIsCorrect, Board.PlayerColor.NO_PLAYER.
Referenced by Games.Trylma.ServerTest.calculatingMove, Games.Trylma.ServerTest.ifPlayerCouldMove, socketServer.Player.run.
boolean Game.Game.playerStillPlaying(int playerId)
Checks if given player is still playing the game playerId player we are checking true if player is still in the game
void Game.Game.resetFieldsStatus()
Resets all board fields status (Sets it to inactive)
References Board.StatusColor.INACTIVE.
void Game.Game.sendToPlayers(String message)
Sends the message to all players message message we want to send
void Game.Game.sendToPlayer(int id, String message)
Sends message only to given player id player id message message we want to send
Board Game.Game.getBoard()
returns this game board
Referenced by Games.Trylma.ServerTest.calculatingMove, Games.Trylma.ServerTest.whoWinTheGame.
void Game.Game.setCurrentPlayer(int id)
Sets id of current player to id of given player id given player id
Referenced by Games.Trylma.ServerTest.ifPlayerCouldMove, Games.Trylma.ServerTest.setAvailableFields.
TrylmaRules Game.Game.getRules()
returns ruleset of this game
Referenced by Games.Trylma.ServerTest.setAvailableFields, Games.Trylma.ServerTest.whoWinTheGame.