Board::DefaultBoard
void Board.DefaultBoard.setFields(ArrayList< BoardField > fields)
Sets the array list of board fields fields the fields that will replace current ones
References Board.Board.fields.
Referenced by Board.DefaultBoardBuilder.initializeBoardFields, Board.DefaultBoardBuilder.setBoardFields.
void Board.DefaultBoard.setStartFields(DefaultStartFields startFields)
Sets the start fields of the board startFields start fields of the board
References Board.Board.startFields.
Referenced by Board.DefaultBoardBuilder.initializeBoardFields.