socketClient::SocketClient
PlayerColor socketClient.SocketClient.playerColor
Referenced by socketClient.SocketClient.getPlayerColor, socketClient.SocketClient.listenSocket, socketClient.SocketClient.setPlayerColor.
PrintWriter socketClient.SocketClient.out
Referenced by board.DefaultBoard.DefaultBoard, socketClient.SocketClient.setUp.
Scanner socketClient.SocketClient.scanner
Referenced by socketClient.SocketClient.listenSocket, socketClient.SocketClient.play, socketClient.SocketClient.setUp.
DataInputStream socketClient.SocketClient.input
Referenced by socketClient.SocketClient.setUp.
ApplicationWindow socketClient.SocketClient.appWindow
Socket socketClient.SocketClient.socket
Referenced by socketClient.SocketClient.setUp.
int socketClient.SocketClient.port
Referenced by socketClient.SocketClient.setUp, socketClient.SocketClient.SocketClient.
socketClient.SocketClient.SocketClient(int port)
Basic constructor.
References socketClient.SocketClient.port, socketClient.SocketClient.setUp.
void socketClient.SocketClient.listenSocket()
Connects to the socket, receives data, that is needed to start the game, from the server.
References frontend.ApplicationWindow.getBoard, socketClient.SocketClient.playerColor, socketClient.SocketClient.scanner, board.Board.setPlayer, socketClient.SocketClient.setPlayerColor.
Referenced by socketClient.TrylmaClient.main.
void socketClient.SocketClient.play()
Takes suitable actions according to data received from the server
References frontend.ApplicationWindow.getBoard, socketClient.SocketClient.scanner, frontend.ApplicationWindow.setBoard, frontend.ApplicationWindow.setCurrPlayer.
Referenced by socketClient.TrylmaClient.main.
void socketClient.SocketClient.setUp()
Sets up all necessary tools
References socketClient.SocketClient.input, socketClient.SocketClient.out, socketClient.SocketClient.port, socketClient.SocketClient.scanner, socketClient.SocketClient.socket.
Referenced by socketClient.SocketClient.SocketClient.
PlayerColor socketClient.SocketClient.getPlayerColor()
returns our color
References socketClient.SocketClient.playerColor.
Referenced by board.DefaultBoard.DefaultBoard.
void socketClient.SocketClient.setPlayerColor(int playerColor)
Sets our color based on data received from the server playerColor id of our color
References board.PlayerColor.fromInteger, socketClient.SocketClient.playerColor.
Referenced by socketClient.SocketClient.listenSocket.