Game::TrylmaRules
ArrayList<Integer> Game.TrylmaRules.availableFields
Referenced by Game.TrylmaRules.getAvailableFields, Game.TrylmaRules.moveIsCorrect.
final int Game.TrylmaRules.playersCount
Referenced by Game.TrylmaRules.isStartingFieldInTargetTriangle, Game.TrylmaRules.isWinner, Game.TrylmaRules.TrylmaRules.
Game.TrylmaRules.TrylmaRules(int playersCount)
Basic constructor playersCount amount of players playing the game
References Game.TrylmaRules.playersCount.
boolean Game.TrylmaRules.isStartingFieldInTargetTriangle(Board board, int startMoveField, int currentPlayer)
Checks if given field is in target area board current board startMoveField the field player is on currentPlayer id of the current player true if field is in target area
References Board.BoardField.getColumn, Board.BoardField.getRow, Game.TrylmaRules.playersCount.
boolean Game.TrylmaRules.isWinner(Game game, int currentPlayer)
Rule set that determines if given player won the game game the game that is being played playerID id of player being checked true if player won the game
References Board.PlayerColor.fromInteger, Game.TrylmaRules.playersCount.
Referenced by Games.Trylma.ServerTest.whoWinTheGame.
boolean Game.TrylmaRules.moveIsCorrect(Board board, int endMoveField)
Rule set that determines if given move is correct. Checks if selected field is in Available fields. It is checked after second click by current player. board the game board in current state endMoveField the field player is trying to move to true if move is correct
References Game.TrylmaRules.availableFields.
Referenced by Game.Game.move.
synchronized void Game.TrylmaRules.setAvailableFields(Board board, BoardField currField, boolean isFirstCheck)
Rule set that maps legal fields that you can move to from selected field. It is checked after first click by current player. board startField isFirstCheck
References Game.TrylmaRules.findNeighbors, Board.PlayerColor.NO_PLAYER, Game.TrylmaRules.tryToJump.
Referenced by Game.TrylmaRules.tryToJump.
synchronized void Game.TrylmaRules.tryToJump(Board board, BoardField currField, BoardField fieldToPass)
Rules responsible for jumping Adds fields you can jump on to available fields board current board currField field we are on fieldToPass field we want to jump over
References Game.TrylmaRules.findNeighbors, Board.BoardField.getColumn, Board.BoardField.getRow, Board.PlayerColor.NO_PLAYER, Game.TrylmaRules.setAvailableFields.
Referenced by Game.TrylmaRules.setAvailableFields.
synchronized ArrayList<BoardField> Game.TrylmaRules.findNeighbors(Board board, BoardField currField)
Finds all neighbors of given field and returns them in form of an array list board current board currField field we are on all fields that are neighbors to currField
References Board.BoardField.getColumn, Board.BoardField.getRow.
Referenced by Game.TrylmaRules.setAvailableFields, Game.TrylmaRules.tryToJump.
ArrayList<Integer> Game.TrylmaRules.getAvailableFields()
returns all available fields
References Game.TrylmaRules.availableFields.
Referenced by Games.Trylma.ServerTest.setAvailableFields.
void Game.TrylmaRules.resetAvailableFields()
Resets available fields after each move