Board::JSONBoardConverter
final StringBuilder Board.JSONBoardConverter.jsonBuilder
Referenced by Board.JSONBoardConverter.addContent.
String Board.JSONBoardConverter.buildJSONBoard(Board board)
Converts a board to a JSON String board board we want to convert JSON String that stores board data
References Board.JSONBoardConverter.addContent, Board.BoardField.getColumn, Board.BoardField.getPlayerColor, Board.BoardField.getRow, Board.BoardField.getStatusColor, Board.BoardField.getXPosition, Board.BoardField.getYPosition, Board.PlayerColor.playerColorID, Board.StatusColor.statusColorID.
Referenced by Games.Trylma.ServerTest.calculatingMove, Game.Game.getInitializationData, Game.Game.move, Game.Game.showPossibilities.
void Board.JSONBoardConverter.addContent(String content)
Ads data to the JSON String content data to add
References Board.JSONBoardConverter.jsonBuilder.
Referenced by Board.JSONBoardConverter.buildJSONBoard.