frontend::PlayerInfoPanel
JLabel frontend.PlayerInfoPanel.playerColorInfo
Referenced by frontend.PlayerInfoPanel.PlayerInfoPanel.
JLabel frontend.PlayerInfoPanel.descriptionPlayer
Referenced by frontend.PlayerInfoPanel.PlayerInfoPanel.
JLabel frontend.PlayerInfoPanel.currentPlayerInfo
Referenced by frontend.PlayerInfoPanel.PlayerInfoPanel.
JLabel frontend.PlayerInfoPanel.descriptionCurrent
Referenced by frontend.PlayerInfoPanel.PlayerInfoPanel.
frontend.PlayerInfoPanel.PlayerInfoPanel(PlayerColor playerColor)
Basic constructor Sets which player are we playerColor our id
References frontend.PlayerInfoPanel.currentPlayerInfo, frontend.PlayerInfoPanel.descriptionCurrent, frontend.PlayerInfoPanel.descriptionPlayer, frontend.PlayerInfoPanel.getColor, frontend.PlayerInfoPanel.playerColorInfo.
void frontend.PlayerInfoPanel.setCurrentPlayerInfo(PlayerColor currPlayerColor)
Changes displayed info about current player currPlayerColor color of a current player
References frontend.PlayerInfoPanel.getColor.
Referenced by frontend.ApplicationWindow.setCurrPlayer.
Color frontend.PlayerInfoPanel.getColor(PlayerColor playerColor)
Provides right color based on color enum playerColor enum of player color Color associated with the enum
Referenced by frontend.PlayerInfoPanel.PlayerInfoPanel, frontend.PlayerInfoPanel.setCurrentPlayerInfo.