.TH "Board.PlayerColor" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Board.PlayerColor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerColor\fP (int \fBplayerColorID\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPlayerColor\fP \fBfromInteger\fP (int x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBLUE\fP =(1)"
.br
.ti -1c
.RI "\fBGREEN\fP =(2)"
.br
.ti -1c
.RI "\fBYELLOW\fP =(3)"
.br
.ti -1c
.RI "\fBORANGE\fP =(4)"
.br
.ti -1c
.RI "\fBPINK\fP =(5)"
.br
.ti -1c
.RI "\fBPURPLE\fP =(6)"
.br
.ti -1c
.RI "\fBNO_PLAYER\fP =(7)"
.br
.ti -1c
.RI "final int \fBplayerColorID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enum with possible player colors 
.PP
Definition at line 7 of file PlayerColor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Board\&.PlayerColor\&.PlayerColor (int playerColorID)"
Each color is associated with a number (id) 
.PP
\fBParameters\fP
.RS 4
\fIplayerColorID\fP color id 
.RE
.PP

.PP
Definition at line 23 of file PlayerColor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBPlayerColor\fP Board\&.PlayerColor\&.fromInteger (int x)\fC [static]\fP"
Converts a number to a color 
.PP
\fBParameters\fP
.RS 4
\fIx\fP number given to convert 
.RE
.PP
\fBReturns\fP
.RS 4
color associated with a given number 
.RE
.PP

.PP
Definition at line 33 of file PlayerColor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "Board\&.PlayerColor\&.BLUE =(1)"

.PP
Definition at line 8 of file PlayerColor\&.java\&.
.SS "Board\&.PlayerColor\&.GREEN =(2)"

.PP
Definition at line 9 of file PlayerColor\&.java\&.
.SS "Board\&.PlayerColor\&.NO_PLAYER =(7)"

.PP
Definition at line 14 of file PlayerColor\&.java\&.
.SS "Board\&.PlayerColor\&.ORANGE =(4)"

.PP
Definition at line 11 of file PlayerColor\&.java\&.
.SS "Board\&.PlayerColor\&.PINK =(5)"

.PP
Definition at line 12 of file PlayerColor\&.java\&.
.SS "final int Board\&.PlayerColor\&.playerColorID"

.PP
Definition at line 16 of file PlayerColor\&.java\&.
.SS "Board\&.PlayerColor\&.PURPLE =(6)"

.PP
Definition at line 13 of file PlayerColor\&.java\&.
.SS "Board\&.PlayerColor\&.YELLOW =(3)"

.PP
Definition at line 10 of file PlayerColor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
