.TH "Board.StatusColor" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Board.StatusColor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatusColor\fP (int \fBstatusColorID\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStatusColor\fP \fBfromInteger\fP (int x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBACTIVE\fP =(1)"
.br
.ti -1c
.RI "\fBINACTIVE\fP =(2)"
.br
.ti -1c
.RI "\fBPOSSIBLE_MOVE\fP =(3)"
.br
.ti -1c
.RI "final int \fBstatusColorID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enum with possible status colors 
.PP
Definition at line 7 of file StatusColor\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Board\&.StatusColor\&.StatusColor (int statusColorID)"
Each status is associated with a number (id) 
.PP
\fBParameters\fP
.RS 4
\fIstatusColorID\fP status id 
.RE
.PP

.PP
Definition at line 19 of file StatusColor\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBStatusColor\fP Board\&.StatusColor\&.fromInteger (int x)\fC [static]\fP"
Converts a number to a status 
.PP
\fBParameters\fP
.RS 4
\fIx\fP number given to convert 
.RE
.PP
\fBReturns\fP
.RS 4
status associated with a given number 
.RE
.PP

.PP
Definition at line 29 of file StatusColor\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "Board\&.StatusColor\&.ACTIVE =(1)"

.PP
Definition at line 8 of file StatusColor\&.java\&.
.SS "Board\&.StatusColor\&.INACTIVE =(2)"

.PP
Definition at line 9 of file StatusColor\&.java\&.
.SS "Board\&.StatusColor\&.POSSIBLE_MOVE =(3)"

.PP
Definition at line 10 of file StatusColor\&.java\&.
.SS "final int Board\&.StatusColor\&.statusColorID"

.PP
Definition at line 12 of file StatusColor\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
