.TH "TrylmaClient/src/main/java/frontend Directory Reference" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrylmaClient/src/main/java/frontend Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBApplicationWindow\&.java\fP"
.br
.ti -1c
.RI "file \fBPlayerInfoPanel\&.java\fP"
.br
.in -1c
