.TH "Games.Trylma.ServerTest" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Games.Trylma.ServerTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcalculatingMove\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBwhoWinTheGame\fP ()"
.br
.ti -1c
.RI "void \fBifPlayerCouldMove\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBsetAvailableFields\fP ()  throws IOException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayer\fP \fBcreateMockedPlayer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file ServerTest\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void Games\&.Trylma\&.ServerTest\&.calculatingMove () throws IOException"

.PP
Definition at line 23 of file ServerTest\&.java\&.
.SS "\fBPlayer\fP Games\&.Trylma\&.ServerTest\&.createMockedPlayer ()\fC [protected]\fP"

.PP
Definition at line 144 of file ServerTest\&.java\&.
.SS "void Games\&.Trylma\&.ServerTest\&.ifPlayerCouldMove () throws IOException"

.PP
Definition at line 88 of file ServerTest\&.java\&.
.SS "void Games\&.Trylma\&.ServerTest\&.setAvailableFields () throws IOException"

.PP
Definition at line 115 of file ServerTest\&.java\&.
.SS "void Games\&.Trylma\&.ServerTest\&.whoWinTheGame ()"

.PP
Definition at line 50 of file ServerTest\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
