.TH "TrylmaServer/src/main/java/socketServer/SocketServer.java" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrylmaServer/src/main/java/socketServer/SocketServer.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsocketServer\&.SocketServer\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBsocketServer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
