.TH "socketClient.TrylmaClient" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socketClient.TrylmaClient
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Client class that sets the socket and runs the app\&. It needs server port passed as an argument\&. 
.PP
Definition at line 9 of file TrylmaClient\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void socketClient\&.TrylmaClient\&.main (String[] args)\fC [static]\fP"
Runs the app Server port must be passed as an argument 
.PP
\fBParameters\fP
.RS 4
\fIargs\fP you have to pass the server port 
.RE
.PP

.PP
Definition at line 17 of file TrylmaClient\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
