.TH "socketServer.Trylma" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socketServer.Trylma
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws Exception "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Trylma\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void socketServer\&.Trylma\&.main (String[] args) throws Exception\fC [static]\fP"

.PP
Definition at line 4 of file Trylma\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
