.TH "socketClient" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socketClient
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocketClient\fP"
.br
.ti -1c
.RI "class \fBTrylmaClient\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
