.TH "socketServer.TrylmaServerWindow" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socketServer.TrylmaServerWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame, and ActionListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBactionPerformed\fP (ActionEvent e)"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBTrylmaServerWindow\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "\fBSocketServer\fP \fBserver\fP"
.br
.ti -1c
.RI "JPanel \fBcontainer\fP"
.br
.ti -1c
.RI "JButton \fBstartTheServer\fP"
.br
.ti -1c
.RI "JTextField \fBportSetter\fP"
.br
.ti -1c
.RI "int \fBport\fP = 1111"
.br
.ti -1c
.RI "ButtonGroup \fBnumOfPlayers\fP"
.br
.ti -1c
.RI "JRadioButton \fBplayers2\fP"
.br
.ti -1c
.RI "JRadioButton \fBplayers3\fP"
.br
.ti -1c
.RI "JRadioButton \fBplayers4\fP"
.br
.ti -1c
.RI "JRadioButton \fBplayers6\fP"
.br
.ti -1c
.RI "int \fBnumberOfPlayers\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Server GUI Gathers information necessary to run the socket server such as server port, amount of players, size of the board\&. After that it runs socket server\&. 
.PP
Definition at line 16 of file TrylmaServerWindow\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "socketServer\&.TrylmaServerWindow\&.TrylmaServerWindow ()\fC [package]\fP"
Basic constructor\&. Sets all components and adds listener to them\&. 
.PP
Definition at line 40 of file TrylmaServerWindow\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void socketServer\&.TrylmaServerWindow\&.actionPerformed (ActionEvent e)"

.PP
Definition at line 97 of file TrylmaServerWindow\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "JPanel socketServer\&.TrylmaServerWindow\&.container\fC [package]\fP"

.PP
Definition at line 18 of file TrylmaServerWindow\&.java\&.
.SS "int socketServer\&.TrylmaServerWindow\&.numberOfPlayers = 2\fC [package]\fP"

.PP
Definition at line 29 of file TrylmaServerWindow\&.java\&.
.SS "ButtonGroup socketServer\&.TrylmaServerWindow\&.numOfPlayers\fC [package]\fP"

.PP
Definition at line 24 of file TrylmaServerWindow\&.java\&.
.SS "JRadioButton socketServer\&.TrylmaServerWindow\&.players2\fC [package]\fP"

.PP
Definition at line 25 of file TrylmaServerWindow\&.java\&.
.SS "JRadioButton socketServer\&.TrylmaServerWindow\&.players3\fC [package]\fP"

.PP
Definition at line 26 of file TrylmaServerWindow\&.java\&.
.SS "JRadioButton socketServer\&.TrylmaServerWindow\&.players4\fC [package]\fP"

.PP
Definition at line 27 of file TrylmaServerWindow\&.java\&.
.SS "JRadioButton socketServer\&.TrylmaServerWindow\&.players6\fC [package]\fP"

.PP
Definition at line 28 of file TrylmaServerWindow\&.java\&.
.SS "int socketServer\&.TrylmaServerWindow\&.port = 1111\fC [package]\fP"

.PP
Definition at line 22 of file TrylmaServerWindow\&.java\&.
.SS "JTextField socketServer\&.TrylmaServerWindow\&.portSetter\fC [package]\fP"

.PP
Definition at line 21 of file TrylmaServerWindow\&.java\&.
.SS "\fBSocketServer\fP socketServer\&.TrylmaServerWindow\&.server\fC [package]\fP"

.PP
Definition at line 17 of file TrylmaServerWindow\&.java\&.
.SS "JButton socketServer\&.TrylmaServerWindow\&.startTheServer\fC [package]\fP"

.PP
Definition at line 19 of file TrylmaServerWindow\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
