.TH "TrylmaClient/src/main/java/socketClient/TrylmaClient.java" 3 "Thu Jan 27 2022" "Trylma" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrylmaClient/src/main/java/socketClient/TrylmaClient.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsocketClient\&.TrylmaClient\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBsocketClient\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Trylma from the source code\&.
